MATIFIREofficiel/SurvivorNext

- SurvivorNext/Pages/DashboardPage.js
- SurvivorNext/Pages/DrawerMenu.js
add a dashboard page with a simple view and text tag
> feat(DashboardPage): add a dashboard in drawer

- .gitignore
- SurvivorNext/Pages/LoginPage.js
- SurvivorNext/Pages/ProfileDetailsScreen.js
- SurvivorNext/Pages/ProfilePage.js
- SurvivorNext/Pages/Trombinoscope.js
- SurvivorNext/babel.config.js
- SurvivorNext/package.json
replace hard coded password, url to env value.
Improvement of the security.
> feat(Pages): add .env for the security during API request

- SurvivorNext/Pages/LoginPage.js
Handle the problem when the user put Maj with email, now it's work.
> feat(Login page): email can be in MAJ or not

- SurvivorNext/Pages/LoginPage.js
Change the detection area of the text, now we can click anywhere inside button to start to write.
> feat(Login Page): change text detection area

- SurvivorNext/Index.js
- SurvivorNext/Pages/DashboardPage.js
- SurvivorNext/package.json
add to dashboard screen a modal screen with an exemple of widgets
> [dashboard]:  add a bottom modal sheet in dashboard

- SurvivorNext/Pages/Trombinoscope.js
Put images of the trombinoscope in the middle of the screen on Android
> feat(Trombinoscope): Improved image display

- SurvivorNext/Pages/DashboardPage.js
The widgets clicked on the modal appear on dashboard screen
> [dashboard]: when we clicked on a widget in the modal, add it in dashboard

- SurvivorNext/Pages/LoginPage.js
Fix the visibility of the text cursor.
Center the text cursor.
> fix(Login Page): fix invisible cursor and center text cursor

- SurvivorNext/Pages/Trombinoscope.js
be able to search for an employer by name or first name
> feat(trombinoscope): add search bar

- SurvivorNext/Pages/LoginPage.js
- SurvivorNext/Pages/ProfileDetailsScreen.js
- SurvivorNext/Pages/ProfilePage.js
- SurvivorNext/Pages/Trombinoscope.js
remove the access token in the .env file and store it locally
> fix(Token): store the access token locally

- SurvivorNext/Pages/LoginPage.js
Fix the visibility of the text cursor for password.
Add the possibility to enter and connect with keyboard 'enter'
> fix(Login Page): cursor visibility and Keyboard 

- SurvivorNext/App.js
- SurvivorNext/babel.config.js
in the babel file some presets make an non-std C++ error and have no impact of the project, so we have to delete it
> fix(Babel): rm the problematic presets

- SurvivorNext/Pages/CalendarPage.js
- SurvivorNext/Pages/DrawerMenu.js
- SurvivorNext/package.json
> feat(Calendar): add a calendar in the drawer CalendarPage

- SurvivorNext/Components/WeatherWidget.js
- SurvivorNext/Pages/DashboardPage.js
the bug is fixed on android and work on ios
> fix(WeatherWidget): fix the bug on android for textInput

- SurvivorNext/Components/JokeWidget.js
- SurvivorNext/Pages/DashboardPage.js
the drawer apparition is changed
> feat(Dashboard): change the modal apparition

- SurvivorNext/Pages/DrawerMenu.js
- SurvivorNext/Pages/ProfilePage.js
chnage the route for request and the variable for image request
> feat(ProfilePage): change the route

- SurvivorNext/AppContext.js
- SurvivorNext/Pages/AdminPanel.js
- SurvivorNext/Pages/LoginPage.js
Delete forgot button useless.
Change theme in Admin Panel
> feat(Admin Panel): change application theme available

- SurvivorNext/AppContext.js
- SurvivorNext/Pages/DashboardPage.js
when we click on the delete button, widgets disappeared
> [dashboard] button for delete the widget

- SurvivorNext/Pages/DashboardPage.js
> feat(Dashboard): the modal disapeared when a widget is selected

- SurvivorNext/Components/DeviseConvertWidget.js
> feat(DeviseConverter): remove the padding in text input

- SurvivorNext/AppContext.js
- SurvivorNext/Components/CustomDrawerHeader.js
- SurvivorNext/Pages/LoginPage.js
fix logo visibility for basic user.
Handle permission to change logo only for admin
> feat(CustomDrawerHeader): logo visibility

- SurvivorNext/Components/FactWidget.js
- SurvivorNext/Components/JokeWidget.js
- SurvivorNext/Components/WeatherWidget.js
- SurvivorNext/Components/isAdmin.js
- SurvivorNext/Pages/LoginPage.js
- SurvivorNext/Pages/ProfileDetailsScreen.js
- SurvivorNext/Pages/ProfilePage.js
- SurvivorNext/Pages/Trombinoscope.js
Delete button forgot password in the Login Page
> fix(Login Page): delete useless button forgot password

- SurvivorNext/Pages/DrawerMenu.js
the color was not visible on TV
> feat(DrawerPage): change the color
